author:
  email: 'jzerbe@vraidsys.com'
  name: 'Jason Zerbe'
description: 'Generalist getting to yes. Splitboarder and trail mountain biker.'
future: true
permalink: /:year/:month/:title/
plugins: [jekyll-gist]
program:
  business:
    anytimemb: https://www.awin1.com/cread.php?awinmid=61685&awinaffid=2042851&ued=https%3A%2F%2Fwww.anytimemailbox.com%2Flocations
    ipostal1: https://ipostal1.com/?ref=4037
    wise: https://wise.prf.hn/l/6lo8oEQ
  card:
    amex: https://americanexpress.com/en-us/referral/JASONZYEnT?XLINK=MYCP
sidebar:
  github:
    link: https://github.com/jzerbe
  linkedin:
    link: https://www.linkedin.com/in/jzerbe
  vraidsys:
    link: https://vraidsys.com
tagline: 'data dirt dollars'
title: JZ
url: https://jzerbe.com
